[package]
name    = "deltaworld"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dw"
path = "source/main.rs"

[profile.release]
lto = true

[dependencies]
gl   = "0.14.0"
glfw = "0.51.0"
libc = "0.2.144"
